import { runPsqlJson } from "../src/db/psql";
import {
  type CvDraftJobRow,
  buildCvDraftSourceSql,
  buildInsertCvDraftSql,
  renderCvDraftMarkdown,
} from "../src/pipeline/cvDraft";

interface CvDraftOptions {
  jobId: string | null;
  maxBullets: number;
  dryRun: boolean;
  json: boolean;
}

interface InsertedDraftRow {
  id: string;
  job_id: string;
  status: string;
  generated_at: string;
}

function readStringFlag(args: string[], name: string): string | null {
  const index = args.indexOf(name);
  if (index === -1) return null;

  const value = args[index + 1];
  if (!value || value.startsWith("--")) {
    throw new Error(`${name} requires a value`);
  }

  return value;
}

function readNumberFlag(args: string[], name: string, fallback: number): number {
  const value = readStringFlag(args, name);
  if (value === null) return fallback;

  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    throw new Error(`${name} must be a positive integer`);
  }

  return parsed;
}

function parseOptions(args: string[]): CvDraftOptions {
  return {
    jobId: readStringFlag(args, "--job-id"),
    maxBullets: readNumberFlag(args, "--max-bullets", 6),
    dryRun: args.includes("--dry-run"),
    json: args.includes("--json"),
  };
}

function printUsage(): void {
  console.log(`Usage:
  bun run cv:draft -- --job-id 1
  bun run cv:draft -- --job-id 1 --max-bullets 4 --dry-run
  bun run cv:draft -- --job-id 1 --json

Options:
  --job-id       Job id from Postgres.
  --max-bullets  Maximum approved bullet blocks to include. Defaults to 6.
  --dry-run      Print the draft without storing it.
  --json         Print machine-readable output.

Drafts are composed only from approved cv_bullet_blocks and remain in needs_human_review state.`);
}

async function run(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.includes("--help") || args.includes("-h")) {
    printUsage();
    return;
  }

  const options = parseOptions(args);
  if (options.jobId === null) {
    throw new Error("--job-id is required");
  }

  const row = await runPsqlJson<CvDraftJobRow | null>(
    buildCvDraftSourceSql(options.jobId, options.maxBullets),
  );
  if (row === null) {
    throw new Error(`No job found with id ${options.jobId}`);
  }

  const draft = renderCvDraftMarkdown(row, {
    generatedAt: new Date(),
    maxBullets: options.maxBullets,
  });

  if (options.dryRun) {
    if (options.json) {
      console.log(JSON.stringify({ stored: false, draft }, null, 2));
      return;
    }
    console.log(draft.markdown.trimEnd());
    return;
  }

  const inserted = await runPsqlJson<InsertedDraftRow>(
    buildInsertCvDraftSql(options.jobId, draft, "Generated by cv:draft; requires human review."),
  );

  if (options.json) {
    console.log(JSON.stringify({ stored: true, inserted, draft }, null, 2));
    return;
  }

  console.log(`Stored CV draft ${inserted.id} for job ${inserted.job_id} (${inserted.status}).`);
  console.log("");
  console.log(draft.markdown.trimEnd());
}

run().catch((err) => {
  console.error(err instanceof Error ? err.stack : err);
  process.exitCode = 1;
});
